### ISSUE TITLE
Add postBuild file so this works on mybinder.org

### ISSUE THREAD

**Issue by villares** [shoebot/jupyter-shoebot#12]
Allison Parrish has been teaching using Flat + a helper library she made called Bezmerizing
https://github.com/aparrish/bezmerizing/blob/master/demo.ipynb

She can lauch a Binder that installs the environment: https://mybinder.org/v2/gh/aparrish/material-of-language/master
[Updated the link, this is the right repo]

That would be amazing if we could do that with shoebot, for teaching...

**Comment by rlafuente** [comment]
I went through the Binder docs and *think* that the way to install the missing dependencies is through the [apt.txt file](https://mybinder.readthedocs.io/en/latest/using/config_files.html#apt-txt-install-packages-with-apt-get). Trying it out now

**Comment by rlafuente** [comment]
ok i added apt.txt and postBuild (to install the shoebot kernel into Jupyter) and the binder notebook is actually running!

however the shoebot kernel does not launch -- it's stuck at "Kernel starting, please wait..." and then disconnects from the server (the kernel runs fine in a local install)

there is one notebook that doesn't use the kernel (shoebot-as-python-module) which might be able to help pinpoint the cause. I'm stuck with this error on the line `import shoebot`:

```
/srv/conda/envs/notebook/lib/python3.7/site-packages/shoebot/core/__init__.py in <module>
     36 """
     37 
---> 38 from canvas import Canvas
     39 from cairo_canvas import CairoCanvas
     40 

ModuleNotFoundError: No module named 'canvas'
```

Also, when running that example locally, I get:

```
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-55561089cd27> in <module>
      2 
      3 import shoebot
----> 4 import cairocffi as cairo
      5 from io import BytesIO
      6 from IPython.display import Image, SVG, display

ModuleNotFoundError: No module named 'cairocffi'
```
...which means that locally it can import shoebot but fails on cairocffi. 

I'm a bit tired to go on for today. In any case, the problem might be that we're hitting binder's memory limits -- let's hope not :/

**Comment by rlafuente** [comment]
Jeez just found out that Stuart did all this in [this PR](https://github.com/shoebot/jupyter-shoebot/pull/13/]

I'll try it tonight, but wondering how it's working for you @stuaxo ?

**Comment by stuaxo** [comment]
Try the PR, for now it pulls in shoebot from GitHub.

Some bits get an exception in drawqueue but that's more that some changes in shoebot are needed.

**Comment by stuaxo** [comment]
Done :)
